pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    timeout(time: 5, unit: 'MINUTES')
    ansiColor('xterm')
  }
  stages {
    stage('Build') {
      steps {
        sh '''
          : ===  "\u001B[31mBuilding in red\u001B[0m"
          : === "Plain color"
        '''
      }
    }
  }
}
